[package]
name = "Filter_FASTQ_By_Average_Base_Quality"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
bio = "0.39.2"
stats-cli = "3.0.1"
